name: YouTube Video Checker

on:
  schedule:
    # This will run the workflow every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  check_videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Run YouTube checker script
        run: |
          python "line rider scraper.py"
